# ----------------------------------------------------------------------
# cloudbuild.yaml for TypeScript/Node.js Docker Build
# ----------------------------------------------------------------------
steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Docker-Build
  args:
    - '-c'
    - |
      echo "Starting build of version: $TAG_NAME"
      echo "Building API"
      docker build -t gcr.io/$PROJECT_ID/${REPO_NAME}-api:${TAG_NAME} .

  entrypoint: bash

- name: 'gcr.io/cloud-builders/docker'
  id: Docker-Push
  args: 
    - 'push'
    - 'gcr.io/$PROJECT_ID/${REPO_NAME}-api:$TAG_NAME'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Deploy-Test
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud builds triggers run deploy-test-${REPO_NAME}-api \
        --region=global \
        --tag=$TAG_NAME
    
options:
  # If you are using a custom service account, include one of these:
  logging: CLOUD_LOGGING_ONLY 
  # default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
  diskSizeGb: '100' # Increase disk space if you have many dependencies or a large project
